from typing import Annotated

from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


class AgentState(TypedDict):

    # --------------------------------------------------------
    # Messages exchanged during graph execution
    # --------------------------------------------------------

    messages: Annotated[
        list,
        add_messages,
    ]

    # --------------------------------------------------------
    # Current application user
    # --------------------------------------------------------

    user_id: str

    # --------------------------------------------------------
    # Original user question
    # --------------------------------------------------------

    question: str

    # --------------------------------------------------------
    # Final answer generated by the agent
    # --------------------------------------------------------

    final_answer: str

    # --------------------------------------------------------
    # Tool-call trace for UI/debugging
    # --------------------------------------------------------

    tool_calls: list